// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.Data;

#nullable disable

namespace Pos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609100917_SeedProductSizeAndAttribute")]
    partial class SeedProductSizeAndAttribute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pos.Models.Authority", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SystemId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId", "SystemId");

                    b.ToTable("Authority");
                });

            modelBuilder.Entity("Pos.Models.BusinessHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("EndTime")
                        .HasColumnType("real");

                    b.Property<float>("MealTimes")
                        .HasColumnType("real");

                    b.Property<string>("StartTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TimeInterval")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Week")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Business_hours");
                });

            modelBuilder.Entity("Pos.Models.CouponsList", b =>
                {
                    b.Property<string>("OrderNo")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CouponsNo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("OrderNo", "CouponsNo");

                    b.ToTable("Coupons_list");
                });

            modelBuilder.Entity("Pos.Models.Factory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankingDepartment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BusinessRegistrationCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Chairman")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fax")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Factory");
                });

            modelBuilder.Entity("Pos.Models.HandOver", b =>
                {
                    b.Property<string>("No")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<float>("Allowance")
                        .HasColumnType("real");

                    b.Property<float?>("Cash")
                        .HasColumnType("real");

                    b.Property<float?>("Coupons")
                        .HasColumnType("real");

                    b.Property<float?>("CreditCard")
                        .HasColumnType("real");

                    b.Property<float>("GrandTotal")
                        .HasColumnType("real");

                    b.Property<string>("HandOverUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("HandoverDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Point")
                        .HasColumnType("real");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("ServiceCharge")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("No");

                    b.ToTable("Hand_over");
                });

            modelBuilder.Entity("Pos.Models.MaintainLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("DbName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Maintain_log");
                });

            modelBuilder.Entity("Pos.Models.Mix", b =>
                {
                    b.Property<string>("MixNo")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("No")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("MixNo", "No");

                    b.ToTable("Mix");
                });

            modelBuilder.Entity("Pos.Models.Orders", b =>
                {
                    b.Property<string>("No")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("Allowance")
                        .HasColumnType("real");

                    b.Property<float?>("Cash")
                        .HasColumnType("real");

                    b.Property<float?>("Coupons")
                        .HasColumnType("real");

                    b.Property<float?>("CreditCard")
                        .HasColumnType("real");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("GrandTotal")
                        .HasColumnType("real");

                    b.Property<string>("HandOverNo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Point")
                        .HasColumnType("real");

                    b.Property<float>("ServiceCharge")
                        .HasColumnType("real");

                    b.Property<string>("StationNo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.Property<string>("TableNo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("No");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Pos.Models.OrdersDetail", b =>
                {
                    b.Property<string>("No")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<float?>("Discount")
                        .HasColumnType("real");

                    b.Property<float?>("DiscountPrice")
                        .HasColumnType("real");

                    b.Property<string>("ProductNo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("No", "SerialNo");

                    b.ToTable("Orders_detail");
                });

            modelBuilder.Entity("Pos.Models.Payment", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("Change")
                        .HasColumnType("bit");

                    b.Property<bool>("InvoiceDisplay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.ToTable("Payment");

                    b.HasData(
                        new
                        {
                            Code = "CASH",
                            Change = true,
                            InvoiceDisplay = true,
                            Name = "現金"
                        },
                        new
                        {
                            Code = "CARD",
                            Change = false,
                            InvoiceDisplay = true,
                            Name = "信用卡"
                        },
                        new
                        {
                            Code = "POINT",
                            Change = false,
                            InvoiceDisplay = false,
                            Name = "點數折抵"
                        });
                });

            modelBuilder.Entity("Pos.Models.Product", b =>
                {
                    b.Property<string>("No")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<float>("DiscountPrice")
                        .HasColumnType("real");

                    b.Property<string>("Image")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kind")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("Mix")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<bool>("Promotion")
                        .HasColumnType("bit");

                    b.Property<bool>("Shelfing")
                        .HasColumnType("bit");

                    b.Property<string>("Size")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("Stock")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("No");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            No = "D0001",
                            DiscountPrice = 80f,
                            Kind = "01",
                            Mix = false,
                            Name = "美式咖啡",
                            Price = 80f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "D0002",
                            DiscountPrice = 100f,
                            Kind = "01",
                            Mix = false,
                            Name = "拿鐵咖啡",
                            Price = 100f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "D0003",
                            DiscountPrice = 60f,
                            Kind = "01",
                            Mix = false,
                            Name = "紅茶",
                            Price = 60f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "D0004",
                            DiscountPrice = 60f,
                            Kind = "01",
                            Mix = false,
                            Name = "綠茶",
                            Price = 60f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "D0005",
                            DiscountPrice = 80f,
                            Kind = "01",
                            Mix = false,
                            Name = "柳橙汁",
                            Price = 80f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "M0001",
                            DiscountPrice = 180f,
                            Kind = "02",
                            Mix = false,
                            Name = "牛肉麵",
                            Price = 180f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "M0002",
                            DiscountPrice = 150f,
                            Kind = "02",
                            Mix = false,
                            Name = "排骨飯",
                            Price = 150f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "M0003",
                            DiscountPrice = 120f,
                            Kind = "02",
                            Mix = false,
                            Name = "炒飯",
                            Price = 120f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "M0004",
                            DiscountPrice = 160f,
                            Kind = "02",
                            Mix = false,
                            Name = "焗烤義大利麵",
                            Price = 160f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "S0001",
                            DiscountPrice = 60f,
                            Kind = "03",
                            Mix = false,
                            Name = "薯條",
                            Price = 60f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "S0002",
                            DiscountPrice = 80f,
                            Kind = "03",
                            Mix = false,
                            Name = "炸雞塊",
                            Price = 80f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "S0003",
                            DiscountPrice = 70f,
                            Kind = "03",
                            Mix = false,
                            Name = "洋蔥圈",
                            Price = 70f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "T0001",
                            DiscountPrice = 120f,
                            Kind = "04",
                            Mix = false,
                            Name = "提拉米蘇",
                            Price = 120f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        },
                        new
                        {
                            No = "T0002",
                            DiscountPrice = 100f,
                            Kind = "04",
                            Mix = false,
                            Name = "草莓蛋糕",
                            Price = 100f,
                            Promotion = false,
                            Shelfing = true,
                            Status = "0",
                            Stock = false,
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system"
                        });
                });

            modelBuilder.Entity("Pos.Models.ProductAttribute", b =>
                {
                    b.Property<string>("No")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("No", "Code");

                    b.ToTable("Product_Attribute");
                });

            modelBuilder.Entity("Pos.Models.ProductAttributeCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.ToTable("Attribute");

                    b.HasData(
                        new
                        {
                            Code = "HOT",
                            Name = "熱"
                        },
                        new
                        {
                            Code = "ICE",
                            Name = "冰"
                        },
                        new
                        {
                            Code = "WRM",
                            Name = "溫"
                        });
                });

            modelBuilder.Entity("Pos.Models.ProductKind", b =>
                {
                    b.Property<string>("No")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("No");

                    b.ToTable("Product_kind");

                    b.HasData(
                        new
                        {
                            No = "01",
                            Name = "飲料"
                        },
                        new
                        {
                            No = "02",
                            Name = "主食"
                        },
                        new
                        {
                            No = "03",
                            Name = "小點"
                        },
                        new
                        {
                            No = "04",
                            Name = "甜點"
                        });
                });

            modelBuilder.Entity("Pos.Models.ProductSize", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Code = "S",
                            Name = "小"
                        },
                        new
                        {
                            Code = "M",
                            Name = "中"
                        },
                        new
                        {
                            Code = "L",
                            Name = "大"
                        });
                });

            modelBuilder.Entity("Pos.Models.PromotionDuration", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Week")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("No");

                    b.ToTable("Promotion_duration");
                });

            modelBuilder.Entity("Pos.Models.PromotionProduct", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<float?>("Discount")
                        .HasColumnType("real");

                    b.Property<bool?>("MemberOnly")
                        .HasColumnType("bit");

                    b.Property<float?>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductNo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("PromotionNo")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("No");

                    b.ToTable("Promotion_product");
                });

            modelBuilder.Entity("Pos.Models.Reservation", b =>
                {
                    b.Property<string>("No")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<float?>("Attendance")
                        .HasColumnType("real");

                    b.Property<DateTime>("BookDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Member")
                        .HasColumnType("bit");

                    b.Property<string>("Memo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TableNo")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("No");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Pos.Models.StationCash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CashType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HandOverNo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("StationNo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Station_cash");
                });

            modelBuilder.Entity("Pos.Models.StationHost", b =>
                {
                    b.Property<string>("StationNo")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StationNo");

                    b.ToTable("Station_host");

                    b.HasData(
                        new
                        {
                            StationNo = "001",
                            HostName = "1號收銀機"
                        },
                        new
                        {
                            StationNo = "002",
                            HostName = "2號收銀機"
                        });
                });

            modelBuilder.Entity("Pos.Models.StationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HandOverNo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Memo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationNo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Station_log");
                });

            modelBuilder.Entity("Pos.Models.Store", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankingDepartment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BranchNo")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("BusinessRegistrationCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Chairman")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fax")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = "MAIN0001",
                            Address = "台北市信義區幸福路100號",
                            BranchNo = "0001",
                            Chairman = "王大明",
                            Email = "info@happyrest.tw",
                            Name = "幸福小館",
                            Telephone = "02-12345678",
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("Pos.Models.TableSetting", b =>
                {
                    b.Property<string>("No")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Hall")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float?>("SeatNum")
                        .HasColumnType("real");

                    b.Property<string>("Waiter")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("No");

                    b.ToTable("Table_setting");

                    b.HasData(
                        new
                        {
                            No = "A01",
                            Hall = "A區",
                            Name = "A區1號",
                            SeatNum = 2f
                        },
                        new
                        {
                            No = "A02",
                            Hall = "A區",
                            Name = "A區2號",
                            SeatNum = 2f
                        },
                        new
                        {
                            No = "A03",
                            Hall = "A區",
                            Name = "A區3號",
                            SeatNum = 4f
                        },
                        new
                        {
                            No = "A04",
                            Hall = "A區",
                            Name = "A區4號",
                            SeatNum = 4f
                        },
                        new
                        {
                            No = "B01",
                            Hall = "B區",
                            Name = "B區1號",
                            SeatNum = 4f
                        },
                        new
                        {
                            No = "B02",
                            Hall = "B區",
                            Name = "B區2號",
                            SeatNum = 4f
                        },
                        new
                        {
                            No = "B03",
                            Hall = "B區",
                            Name = "B區3號",
                            SeatNum = 6f
                        },
                        new
                        {
                            No = "B04",
                            Hall = "B區",
                            Name = "B區4號",
                            SeatNum = 6f
                        },
                        new
                        {
                            No = "C01",
                            Hall = "包廂",
                            Name = "包廂1",
                            SeatNum = 8f
                        },
                        new
                        {
                            No = "C02",
                            Hall = "包廂",
                            Name = "包廂2",
                            SeatNum = 10f
                        });
                });

            modelBuilder.Entity("Pos.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("IdNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("UserLogin")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = "admin",
                            EmployeeNo = "0001",
                            Name = "管理者",
                            Password = "admin123",
                            Status = "0",
                            UpdateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updater = "system",
                            UserGroup = "管理者",
                            UserLogin = false
                        });
                });

            modelBuilder.Entity("Pos.Models.UserGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User_group");

                    b.HasData(
                        new
                        {
                            Id = "0",
                            Description = "系統管理員，擁有全部權限",
                            Name = "管理者"
                        },
                        new
                        {
                            Id = "1",
                            Description = "可查看交班報表",
                            Name = "班長"
                        },
                        new
                        {
                            Id = "2",
                            Description = "前台收銀操作",
                            Name = "收銀員"
                        });
                });

            modelBuilder.Entity("Pos.Models.OrdersDetail", b =>
                {
                    b.HasOne("Pos.Models.Orders", null)
                        .WithMany("Details")
                        .HasForeignKey("No")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Models.Orders", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
